management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'healthcheck', 'prometheus' ]
      base-path: '/admin'
      path-mapping:
        prometheus: '/metrics'
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_web
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

